language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/movie_list

node_js:  
  - 12

before_script:
  - psql -c 'create database movie_list;' -U postgres
  - psql -U postgres -d movie_list -a -f "movie-table.sql"

services:
  - postgresql